# Generated by Django 2.2 on 2020-12-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('pub_date', models.DateField(verbose_name='发布日期')),
                ('image', models.ImageField(upload_to='avatar', verbose_name='图书封面')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('read', models.IntegerField(verbose_name='阅读量')),
                ('comment', models.IntegerField(verbose_name='评论量')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'tb_book_info',
            },
        ),
    ]
